name: Health Client
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  main:
    defaults:
      run:
        working-directory: health-client
    runs-on: ubuntu-latest
    environment: production
    env:
      REACT_APP_HEALTH_CHECK_SERVICE_URL: ${{ secrets.REACT_APP_HEALTH_CHECK_SERVICE_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: npm install
      - name: install gh-pages
        run: npm install gh-pages      
      - name: create .env.production
        run: echo 'REACT_APP_HEALTH_CHECK_SERVICE_URL=${{ env.REACT_APP_HEALTH_CHECK_SERVICE_URL }}' >> .env.production
      - name: build
        run: npm run build  
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
