name: Health Client
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  main:
    defaults:
      run:
        working-directory: health-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: npm install
      - name: create .env.production
        run: echo 'REACT_APP_HEALTH_CHECK_SERVICE_URL=${{ env.REACT_APP_HEALTH_CHECK_SERVICE_URL }}' >> .env.production
      - name: build
        run: npm run deploy
